# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "Humboldt Native Plants"
name                     : "Humboldt Native Plants"
baseurl                  : /humboldtnativeplants
include                  : ["_pages"]
logo                     : "/assets/images/leaf-icon.png"
collections_dir          : "collections"
collections              : 
    plants: 
        output: true
        permalink: /:collection/:path
    categories:
        output: true
        permalink: /category/:name
defaults:
 - scope:
     type: "plants"
   values:
     title: ""
     layout: plant
 - scope:
     type: "categories"
   values:
     classes: category-page wide
     layout: category
     custom_js:
        - util 
        - plant_data_table
after_footer_scripts     : 
    - https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
    - https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js
