# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "Humboldt County Native Plants"
name                     : "Humboldt County Native Plants"
baseurl                  : /humboldtnativeplants
include                  : ["_pages"]
logo                     : "/assets/images/leaf-icon.png"
