# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title                    : "Humboldt Native Plants"
name                     : "Humboldt Native Plants"
#baseurl                  : /humboldtnativeplants
include                  : ["_pages"]
logo                     : "/assets/images/leaf-icon.png"
collections_dir          : "collections"
collections              : 
    plant_types:
        output: false
    plants: 
        output: true
        permalink: /:collection/:path
    categories:
        output: true
        permalink: /category/:name
    gardens:
        output: true
        permalink: /garden/:name
    nurseries:
        output: true
        permalink: /nursery/:name
    volunteer_opportunities: 
        output: true
        permalink: /volunteer/:name
defaults:
 - scope:
     type: "plants"
   values:
     title: ""
     layout: plant
 - scope:
     type: "categories"
   values:
     classes: layout--splash category-page wide
     layout: category
     custom_js:
        - util 
        - plant_data_table
 - scope:
     type: "gardens"
   values:
     classes: garden-page wide
     title: ""
     layout: garden
 - scope:
     type: "nurseries"
   values:
     classes: nursery-page wide
     title: ""
     layout: nursery
 - scope:
     type: "volunteer_opportunities"
   values:
     classes: volunteer-page wide
     title: ""
     layout: splash
after_footer_scripts     : 
    - https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
    - https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js
